### ISSUE TITLE
Error while syncing ETC full chain

### ISSUE THREAD

**Issue by lowskidev** [ethoxy/multi-geth#65]
Every time I try to sync the ETC mainnet with the `full` flag I start getting these error messages.
Tried this on several machines with 4gb of ram up to 16gb of ram.

Thanks.

#### System information
````
Geth version: `v1.8.21-stable`
OS & Version: Linux 
Commit hash : (if `develop`)
````
````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4fee28]

goroutine 1967 [running]:
math/big.(*Int).Cmp(0x44205bb880, 0x0, 0xb88f87396b49025d)
        /usr/lib/go-1.10/src/math/big/int.go:319 +0x20
github.com/ethereum/go-ethereum/core.(*BlockChain).insertSidechain(0x44248b4000, 0x4432dfd678, 0x44200653b0, 0x4420065301, 0x1, 0x1, 0x4432c35efc, 0x1, 0x1, 0x443259f680, ...)
        /home/rock64/multi-geth-1.8.21-kotti/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:1333 +0xbf8
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0x44248b4000, 0x4432652770, 0x1, 0x1, 0x4420211f01, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/rock64/multi-geth-1.8.21-kotti/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:1139 +0x2248
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0x44248b4000, 0x4432652770, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/rock64/multi-geth-1.8.21-kotti/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:1088 +0x830
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0x44200b4340, 0x442449e578, 0x1, 0x1, 0x1, 0x976b44)
        /home/rock64/multi-geth-1.8.21-kotti/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1490 +0x314
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0x44200b4340, 0x4431f44fa0, 0x4433171d10)
        /home/rock64/multi-geth-1.8.21-kotti/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1464 +0x5c
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).(github.com/ethereum/go-ethereum/eth/downloader.processFullSyncContent)-fm(0x8, 0xefea98)
        /home/rock64/multi-geth-1.8.21-kotti/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:479 +0x20
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0x44200b4340, 0x44329df200, 0x4422f8fb90)
        /home/rock64/multi-geth-1.8.21-kotti/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0x50
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
        /home/rock64/multi-geth-1.8.21-kotti/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0x94
````

**Comment by meowsbits** [comment]
Possibly rel https://github.com/ethereum/go-ethereum/pull/19113/files

I'm going to work on pulling together an upstream merge, maybe we can see if that solves your issue.

**Comment by meowsbits** [comment]
@ethernodeio I'd be curious if the build from #66 seems to resolve your issue.

**Comment by lowskidev** [comment]
Hey thanks, I'll into both of those, I'v been doing some research of my own, let me make sure that this isn't something that just pops up on ARM arch type CPU's and will report right back.

**Comment by lowskidev** [comment]
oh I also just noticed I am running geth 1.8.21 didn't realize there was a .23 release oops, let me updated and try again.

**Comment by lowskidev** [comment]
Upgrading to latest version `.23` seems to have solved my ETC sync issues.

Thank you.
