### ISSUE TITLE
segmentation fault during full sync

### ISSUE THREAD

**Issue by tzdybal** [ethoxy/multi-geth#98]
```
[tomek@tomek multi-geth]$ ./build/bin/geth --classic --cache=16384 --syncmode full
WARN [06-11|09:48:40.812] Sanitizing cache to Go's GC limits       provided=16384 updated=16072
INFO [06-11|09:48:40.813] Maximum peer count                       ETH=50 LES=0 total=50
WARN [06-11|09:48:40.814] Failed to start smart card hub, disabling: dial unix /run/pcscd/pcscd.comm: connect: no such file or directory 
INFO [06-11|09:48:40.827] Starting peer-to-peer node               instance=MultiGeth/v1.9.0-unstable-0bb7fc90-20190610/linux-amd64/go1.12.5
INFO [06-11|09:48:40.827] Allocated trie memory caches             clean=4018.00MiB dirty=4018.00MiB
INFO [06-11|09:48:40.827] Allocated cache and file handles         database=/home/tomek/.ethereum/classic/geth/chaindata cache=8036.00MiB handles=262144
INFO [06-11|09:48:41.280] Persisted trie from memory database      nodes=12356 size=1.79MiB time=36.568106ms gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [06-11|09:48:41.280] Initialised chain configuration          config="{ChainID: 61 Homestead: 1150000 DAO: 1920000 DAOSupport: false EIP150: 2500000 EIP155: 3000000 EIP158: <nil> Byzantium: <nil> Disposal: 5900000 Social: <nil> Ethersocial: <nil> ECIP1017: 5000000 EIP160: 3000000 ECIP1010PauseBlock: 3000000 ECIP1010Length: 2000000 Constantinople: <nil> ConstantinopleFix: <nil> Engine: ethash}"
INFO [06-11|09:48:41.281] Disk storage enabled for ethash caches   dir=/home/tomek/.ethereum/classic/geth/ethash count=3
INFO [06-11|09:48:41.281] Disk storage enabled for ethash DAGs     dir=/home/tomek/.ethash                       count=2
INFO [06-11|09:48:41.281] Initialising Ethereum protocol           versions="[63 62]" network=1 dbversion=6
INFO [06-11|09:48:42.161] Loaded most recent local header          number=3328 hash=ef1d9a…ca5206 td=142069104550127 age=3y11mo1d
INFO [06-11|09:48:42.162] Loaded most recent local full block      number=0    hash=d4e567…cb8fa3 td=17179869184     age=50y1mo4w
INFO [06-11|09:48:42.162] Loaded most recent local fast block      number=3328 hash=ef1d9a…ca5206 td=142069104550127 age=3y11mo1d
INFO [06-11|09:48:42.162] Loaded local transaction journal         transactions=0 dropped=0
INFO [06-11|09:48:42.162] Regenerated local transaction journal    transactions=0 accounts=0
INFO [06-11|09:48:42.195] New local node record                    seq=10 id=e6a1491b7e328ef8 ip=127.0.0.1 udp=30303 tcp=30303
INFO [06-11|09:48:42.195] Started P2P networking                   self=enode://3c46a5558ca04b4053ca181f8444c878ad0ca9aedca6a650ccb836d1ad37509c1516bc40397ee3539b887d23d0aeaa5d4daa6e57076f5e1457dba5632fe30249@127.0.0.1:30303
INFO [06-11|09:48:42.197] IPC endpoint opened                      url=/home/tomek/.ethereum/classic/geth.ipc
INFO [06-11|09:48:50.831] New local node record                    seq=11 id=e6a1491b7e328ef8 ip=89.187.165.142 udp=30303 tcp=30303
INFO [06-11|09:49:12.196] Block synchronisation started 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6a2657]

goroutine 626 [running]:
github.com/ethereum/go-ethereum/trie.(*SyncBloom).Contains(0x0, 0xc10534cde0, 0x20, 0x20, 0x304100000000)
	/home/tomek/devel/go/src/github.com/etclabscore/multi-geth/build/_workspace/src/github.com/ethereum/go-ethereum/trie/sync_bloom.go:182 +0x47
github.com/ethereum/go-ethereum/trie.(*Sync).AddSubTrie(0xc105332e40, 0x91e57d669dfbd024, 0x3ece7565ce1c4375, 0x1c40a5f6a2e99447, 0xaa86c0f64488256d, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/tomek/devel/go/src/github.com/etclabscore/multi-geth/build/_workspace/src/github.com/ethereum/go-ethereum/trie/sync.go:104 +0x12e
github.com/ethereum/go-ethereum/trie.NewSync(0x91e57d669dfbd024, 0x3ece7565ce1c4375, 0x1c40a5f6a2e99447, 0xaa86c0f64488256d, 0x7f807c619228, 0xc0000d62c0, 0xc00044eaf0, 0x0, 0x0)
	/home/tomek/devel/go/src/github.com/etclabscore/multi-geth/build/_workspace/src/github.com/ethereum/go-ethereum/trie/sync.go:91 +0x28e
github.com/ethereum/go-ethereum/core/state.NewStateSync(0x91e57d669dfbd024, 0x3ece7565ce1c4375, 0x1c40a5f6a2e99447, 0xaa86c0f64488256d, 0x7f807c619228, 0xc0000d62c0, 0x0, 0x0)
	/home/tomek/devel/go/src/github.com/etclabscore/multi-geth/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/sync.go:40 +0xb4
github.com/ethereum/go-ethereum/eth/downloader.newStateSync(0xc101fa8000, 0x91e57d669dfbd024, 0x3ece7565ce1c4375, 0x1c40a5f6a2e99447, 0xaa86c0f64488256d, 0x0)
	/home/tomek/devel/go/src/github.com/etclabscore/multi-geth/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/statesync.go:243 +0x8e
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncState(0xc101fa8000, 0x91e57d669dfbd024, 0x3ece7565ce1c4375, 0x1c40a5f6a2e99447, 0xaa86c0f64488256d, 0x0)
	/home/tomek/devel/go/src/github.com/etclabscore/multi-geth/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/statesync.go:63 +0x5a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFastSyncContent(0xc101fa8000, 0xc104b72900, 0x0, 0x0)
	/home/tomek/devel/go/src/github.com/etclabscore/multi-geth/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1535 +0xa5
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func7(0x8, 0x117bb88)
	/home/tomek/devel/go/src/github.com/etclabscore/multi-geth/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0x33
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc101fa8000, 0xc000375f20, 0xc10524b660)
	/home/tomek/devel/go/src/github.com/etclabscore/multi-geth/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:505 +0x59
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
	/home/tomek/devel/go/src/github.com/etclabscore/multi-geth/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:505 +0xaf
```

**Comment by tzdybal** [comment]
First - started node without `--syncmode`. After some time stopped the node and started with `--syncmode full`.
Removed `~/.ethereum/classic` and now it works.
I should try to restart without wiping data :-1:
